### ISSUE TITLE
how to disable the swipe gesture?

### ISSUE THREAD

**Issue by vuevrn** [AlKhokhlov/SwiftyPageController#2]
is there a way to disable a gesture that detects the swipe? It just overlaps the tableview delete swipe.

Or is there a way so that both can persist together?

**Comment by alkhokhlov** [comment]
With new version you can simply delete **panGesture**. If you want the restore pan gesture, just call method **setupPanGesture()**.

**Comment by hardikamal** [comment]
@vuevrn Were you able to solve your issue?

**Comment by hardikamal** [comment]
@alkhokhlov How can I delete the pan gesture?
