### ISSUE TITLE
UI problems after first page swipe

### ISSUE THREAD

**Issue by rursache** [AlKhokhlov/SwiftyPageController#5]
i got 3 view controllers in SwiftyPageController

1. if i switch to VC no. 2, and come back to no. 1, pressing any UIButton will keep it highlighted until a future page change.
2. if i switch to VC no. 2, and come back to no. 1, presenting an alertview will make the app be stuck. you cannot press any button in the alertview

i'm 99% sure both problems have the same root cause

**Comment by alkhokhlov** [comment]
1. added **permissibleRangeForHandlingPanFromSides** for starting handle pan gesture
2. fixed
